import type { ConnectContext, IntegrationProvider, ProviderRecord, ProviderSyncBatch, ProviderSyncState, StoredCredential } from '../types.js';
import { GoogleOAuthClient } from './google-oauth.js';

class GoogleApiError extends Error { constructor(readonly status:number,message:string){super(message)} }
async function api<T>(url:string,credential:StoredCredential):Promise<T>{const response=await fetch(url,{headers:{Authorization:`Bearer ${credential.accessToken}`}});if(!response.ok)throw new GoogleApiError(response.status,`Google API request failed (${response.status})`);return response.json() as Promise<T>}
const header=(payload:any,name:string)=>payload?.headers?.find((h:any)=>String(h.name).toLowerCase()===name.toLowerCase())?.value;
function decodeBody(payload:any):string|undefined{const data=payload?.body?.data??payload?.parts?.find((p:any)=>p.mimeType==='text/plain')?.body?.data;if(!data)return;try{return Buffer.from(String(data).replaceAll('-','+').replaceAll('_','/'),'base64').toString('utf8').slice(0,8000)}catch{return}}

export class GoogleProvider implements IntegrationProvider {
  readonly id='google'; constructor(private readonly oauth:GoogleOAuthClient){}
  connect(context:ConnectContext){void context;return this.oauth.authorize()} reconnect(accountId:string,context:ConnectContext){void accountId;void context;return this.oauth.authorize()} revoke(credential:StoredCredential){return this.oauth.revoke(credential)}
  async sync(_accountId:string,credential:StoredCredential,state:ProviderSyncState){credential=await this.oauth.refresh(credential);const failures:string[]=[];let mail:ProviderRecord[]=[];let calendar:ProviderRecord[]=[];let gmailState:ProviderSyncState={};let calendarState:ProviderSyncState={};
    try{({records:mail,state:gmailState}=await this.syncMail(credential,state))}catch(error){failures.push(this.safeFailure('Gmail',error))}
    try{({records:calendar,state:calendarState}=await this.syncCalendar(credential,state))}catch(error){failures.push(this.safeFailure('Calendar',error))}
    const batch:ProviderSyncBatch={records:[...mail,...calendar],nextState:{...state,...gmailState,...calendarState},failures,mailProcessed:mail.length,calendarProcessed:calendar.length};return{batch,credential};
  }
  private safeFailure(service:string,error:unknown){if(error instanceof GoogleApiError){if(error.status===401)return`${service}: authentication required`;if(error.status===403)return`${service}: permission denied`;if(error.status===429)return`${service}: rate limited; try again later`;return`${service}: Google API error ${error.status}`}return`${service}: network or malformed-data error`}
  private async syncMail(credential:StoredCredential,state:ProviderSyncState){const since=state.gmailLastSyncedAt?`after:${Math.floor(new Date(state.gmailLastSyncedAt).getTime()/1000)}`:'newer_than:30d';const query=`${since} -in:spam -in:trash`;const list=await api<any>(`https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=100&q=${encodeURIComponent(query)}`,credential);const records:ProviderRecord[]=[];for(const item of list.messages??[]){try{const message=await api<any>(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(item.id)}?format=full`,credential);const subject=header(message.payload,'Subject')??'(No subject)';const sender=header(message.payload,'From');const occurredAt=new Date(Number(message.internalDate)).toISOString();records.push({providerResourceId:String(message.id),type:'mail',title:String(subject),sender,occurredAt,sourceUrl:`https://mail.google.com/mail/u/0/#all/${message.id}`,snippet:String(message.snippet??'').slice(0,1000),content:decodeBody(message.payload),providerUpdatedAt:occurredAt,rawMetadata:{threadId:message.threadId,labelIds:message.labelIds??[],to:header(message.payload,'To'),deliveredTo:header(message.payload,'Delivered-To'),originalTo:header(message.payload,'X-Original-To')??header(message.payload,'Original-Recipient'),resentTo:header(message.payload,'Resent-To'),xForwardedTo:header(message.payload,'X-Forwarded-To'),replyTo:header(message.payload,'Reply-To'),listUnsubscribe:header(message.payload,'List-Unsubscribe'),precedence:header(message.payload,'Precedence')}})}catch{/* A malformed/deleted message must not abort the whole mailbox sync. */}}
    const profile=await api<any>('https://gmail.googleapis.com/gmail/v1/users/me/profile',credential);return{records,state:{gmailHistoryId:String(profile.historyId??''),gmailLastSyncedAt:new Date().toISOString()}};
  }
  private async syncCalendar(credential:StoredCredential,state:ProviderSyncState,reset=false):Promise<{records:ProviderRecord[];state:ProviderSyncState}>{const url=new URL('https://www.googleapis.com/calendar/v3/calendars/primary/events');url.searchParams.set('maxResults','250');url.searchParams.set('singleEvents','true');url.searchParams.set('showDeleted','true');if(state.calendarSyncToken&&!reset)url.searchParams.set('syncToken',state.calendarSyncToken);else{url.searchParams.set('timeMin',new Date(Date.now()-30*864e5).toISOString());url.searchParams.set('timeMax',new Date(Date.now()+180*864e5).toISOString())}let payload:any;try{payload=await api<any>(url.toString(),credential)}catch(error){if(error instanceof GoogleApiError&&error.status===410&&!reset)return this.syncCalendar(credential,{...state,calendarSyncToken:undefined},true);throw error}const records:ProviderRecord[]=(payload.items??[]).map((event:any)=>({providerResourceId:String(event.id),type:'calendar-event' as const,title:String(event.summary??'(Untitled event)'),sender:event.organizer?.email,occurredAt:new Date(event.start?.dateTime??`${event.start?.date}T00:00:00`).toISOString(),endAt:new Date(event.end?.dateTime??`${event.end?.date}T00:00:00`).toISOString(),sourceUrl:event.htmlLink,snippet:String(event.description??'').slice(0,1000),content:String(event.description??'').slice(0,8000),location:event.location,calendarId:'primary',providerStatus:event.status??'confirmed',providerUpdatedAt:event.updated,rawMetadata:{iCalUID:event.iCalUID,recurringEventId:event.recurringEventId}}));return{records,state:{calendarSyncToken:payload.nextSyncToken??state.calendarSyncToken}}}
}
