import { integer, real, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

const id = () => text('id').primaryKey();
const timestamps = { createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() };

export const institutions = sqliteTable('institutions', { id: id(), name: text('name').notNull(), shortName: text('short_name').notNull(), ...timestamps }, (t) => [uniqueIndex('institution_short_name').on(t.shortName)]);
export const programs = sqliteTable('programs', { id: id(), institutionId: text('institution_id').notNull().references(() => institutions.id), name: text('name').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps });
export const terms = sqliteTable('terms', { id: id(), programId: text('program_id').notNull().references(() => programs.id), name: text('name').notNull(), startsAt: text('starts_at'), endsAt: text('ends_at'), status: text('status').notNull(), ...timestamps });
export const courses = sqliteTable('courses', { id: id(), institutionId: text('institution_id').notNull().references(() => institutions.id), termId: text('term_id').notNull().references(() => terms.id), code: text('code').notNull(), name: text('name').notNull(), credits: real('credits'), active: integer('active', { mode: 'boolean' }).notNull().default(true), gradingConfig: text('grading_config'), ...timestamps });
export const courseModules = sqliteTable('course_modules', { id: id(), courseId: text('course_id').notNull().references(() => courses.id), weekNumber: integer('week_number').notNull(), title: text('title').notNull(), topics: text('topics').notNull(), completed: integer('completed', { mode: 'boolean' }).notNull().default(false), ...timestamps });
export const assessments = sqliteTable('assessments', { id: id(), courseId: text('course_id').notNull().references(() => courses.id), type: text('type').notNull(), title: text('title').notNull(), scheduledAt: text('scheduled_at'), releaseAt: text('release_at'), peerReviewAt: text('peer_review_at'), score: real('score'), maximumScore: real('maximum_score'), status: text('status').notNull(), notes: text('notes').notNull().default(''), sourceUrl: text('source_url'), ...timestamps });
export const items = sqliteTable('items', { id: id(), title: text('title').notNull(), description: text('description').notNull().default(''), area: text('area').notNull(), courseId: text('course_id').references(() => courses.id), type: text('type').notNull(), status: text('status').notNull(), priority: text('priority').notNull(), dueAt: text('due_at'), source: text('source').notNull(), sourceUrl: text('source_url'), externalRecordId: text('external_record_id'), completedAt: text('completed_at'), ...timestamps });
export const externalRecords = sqliteTable('external_records', { id: id(), provider: text('provider').notNull(), providerAccountId: text('provider_account_id'), providerRecordId: text('provider_record_id').notNull(), providerResourceId: text('provider_resource_id'), type: text('type').notNull(), title: text('title').notNull(), sender: text('sender'), occurredAt: text('occurred_at').notNull(), endAt: text('end_at'), detectedDueAt: text('detected_due_at'), sourceUrl: text('source_url'), snippet: text('snippet'), content: text('content'), location: text('location'), calendarId: text('calendar_id'), providerStatus: text('provider_status').notNull().default('active'), providerUpdatedAt: text('provider_updated_at'), classificationState: text('classification_state').notNull(), rawMetadata: text('raw_metadata'), area: text('area').notNull(), routingState: text('routing_state').notNull().default('included'), routingReason: text('routing_reason'), archived: integer('archived', { mode: 'boolean' }).notNull().default(false), ...timestamps });
export const integrationAccounts = sqliteTable('integration_accounts', { id: id(), provider: text('provider').notNull(), providerAccountId: text('provider_account_id'), label: text('label').notNull(), email: text('email'), area: text('area').notNull(), institutionId: text('institution_id').references(() => institutions.id), scopes: text('scopes').notNull(), status: text('status').notNull(), lastSyncAt: text('last_sync_at'), lastSyncAttemptAt: text('last_sync_attempt_at'), lastSyncError: text('last_sync_error'), syncState: text('sync_state').notNull().default('{}'), metadata: text('metadata'), ...timestamps });
export const institutionMailDomains = sqliteTable('institution_mail_domains', { id: id(), institutionId: text('institution_id').notNull().references(() => institutions.id), domain: text('domain').notNull(), createdAt: text('created_at').notNull() });
export const mailRoutingRules = sqliteTable('mail_routing_rules', { id: id(), integrationAccountId: text('integration_account_id').notNull().references(() => integrationAccounts.id), action: text('action').notNull(), matchType: text('match_type').notNull(), matchValue: text('match_value').notNull(), targetArea: text('target_area'), targetInstitutionId: text('target_institution_id').references(() => institutions.id), priority: integer('priority').notNull().default(100), ...timestamps });
export const reviewProposals = sqliteTable('review_proposals', { id: id(), externalRecordId: text('external_record_id').notNull().references(() => externalRecords.id), kind: text('kind').notNull(), confidence: real('confidence').notNull(), title: text('title').notNull(), courseId: text('course_id').references(() => courses.id), institutionId: text('institution_id').references(() => institutions.id), proposedDueAt: text('proposed_due_at'), proposedData: text('proposed_data').notNull(), reasons: text('reasons').notNull(), status: text('status').notNull(), ...timestamps });
export const appSettings = sqliteTable('app_settings', { key: text('key').primaryKey(), value: text('value').notNull(), updatedAt: text('updated_at').notNull() });
export const portals = sqliteTable('portals', { id: id(), name: text('name').notNull(), url: text('url'), area: text('area').notNull(), enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true), ...timestamps });
