import { afterEach,beforeEach,describe,expect,it } from 'vitest';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { LocalDatabase } from '../database/client.js';
import { runMigrations } from '../database/migrations.js';
import { seedDatabase } from '../database/seed.js';
import { MemoryCredentialStore } from '../integrations/keychain-credential-store.js';
import type { ConnectContext,IntegrationProvider,ProviderSyncState,StoredCredential } from '../integrations/types.js';
import { DeterministicClassifier } from '../classification/classifier.js';
import { CommandCentreService } from './command-centre-service.js';
import { IntegrationService } from './integration-service.js';

const credential:StoredCredential={accessToken:'test-access-token',refreshToken:'test-refresh-token',expiresAt:Date.now()+3600000,tokenType:'Bearer',scopes:['gmail.readonly','calendar.readonly']};
class MockGoogle implements IntegrationProvider {readonly id='google';title='MA1003 Week 1 assignment due 2026-10-31';sender='faculty@study.iitm.ac.in';rawMetadata:Record<string,unknown>={originalTo:'student@study.iitm.ac.in',labelIds:['INBOX']};connect(context:ConnectContext){void context;return Promise.resolve({metadata:{providerAccountId:'google-user-1',email:'personal@example.com',label:'Personal',scopes:credential.scopes},credential})}reconnect(_id:string,c:ConnectContext){return this.connect(c)}revoke(){return Promise.resolve()}sync(_id:string,c:StoredCredential,state:ProviderSyncState){return Promise.resolve({credential:c,batch:{records:[{providerResourceId:'message-1',type:'mail' as const,title:this.title,sender:this.sender,occurredAt:'2026-09-26T10:00:00.000Z',sourceUrl:'https://mail.google.com/mail/u/0/#all/message-1',rawMetadata:this.rawMetadata}],nextState:{...state,gmailLastSyncedAt:'2026-09-26T10:01:00.000Z'},failures:[],mailProcessed:1,calendarProcessed:0}})}}

describe('integration persistence and review',()=>{let dir:string;let db:LocalDatabase;let service:IntegrationService;let provider:MockGoogle;beforeEach(()=>{dir=mkdtempSync(path.join(tmpdir(),'cc-integration-'));db=new LocalDatabase(path.join(dir,'test.sqlite'));runMigrations(db);seedDatabase(db);provider=new MockGoogle();const command=new CommandCentreService(db);service=new IntegrationService(db,new MemoryCredentialStore(),new Map([[provider.id,provider]]),new DeterministicClassifier(),command)});afterEach(()=>{db.close();rmSync(dir,{recursive:true,force:true})});
  it('upserts provider records idempotently and updates changed content',async()=>{const account=await service.connectGoogle({area:'IITM',label:'IITM Google'});await service.sync(account.id);await service.sync(account.id);expect((db.prepare("SELECT count(*) n FROM external_records WHERE provider='google'").get() as any).n).toBe(1);provider.title='MA1003 Updated assignment due 2026-10-31';await service.sync(account.id);expect((db.prepare("SELECT title FROM external_records WHERE provider='google'").get() as any).title).toContain('Updated');});
  it('confirms a proposal into an item and marks it confirmed',async()=>{const account=await service.connectGoogle({area:'IITM',label:'IITM Google'});await service.sync(account.id);const proposal=db.prepare("SELECT id FROM review_proposals WHERE status='pending' AND kind!='new-course' LIMIT 1").get() as any;service.actOnProposal({id:proposal.id,action:'confirm'});const item=db.prepare("SELECT course_id courseId,source,external_record_id externalRecordId FROM items WHERE source_url LIKE 'https://mail.google.com/%'").get() as any;expect(item.courseId).toBeTruthy();expect(item.source).toBe('inbox-email');expect(item.externalRecordId).toBeTruthy();expect((db.prepare('SELECT status FROM review_proposals WHERE id=?').get(proposal.id) as any).status).toBe('confirmed');});
  it('ignores a proposal without creating an item',async()=>{const account=await service.connectGoogle({area:'IITM',label:'IITM Google'});await service.sync(account.id);const proposal=db.prepare("SELECT id FROM review_proposals WHERE status='pending' LIMIT 1").get() as any;const before=(db.prepare('SELECT count(*) n FROM items').get() as any).n;service.actOnProposal({id:proposal.id,action:'ignore'});expect((db.prepare('SELECT count(*) n FROM items').get() as any).n).toBe(before);expect((db.prepare('SELECT status FROM review_proposals WHERE id=?').get(proposal.id) as any).status).toBe('ignored');});
  it('does not let the provider account area blindly determine message area',async()=>{const account=await service.connectGoogle({area:'IITM',label:'Personal transport'});provider.title='Dinner plans';provider.sender='friend@example.net';provider.rawMetadata={to:'personal@example.com',labelIds:['INBOX']};await service.sync(account.id);expect((db.prepare("SELECT area FROM external_records WHERE provider='google'").get() as any).area).toBe('PERSONAL');expect((db.prepare("SELECT count(*) n FROM review_proposals p JOIN external_records e ON e.id=p.external_record_id WHERE e.provider='google'").get() as any).n).toBe(0)});
  it('re-evaluates noisy existing mail idempotently',async()=>{const account=await service.connectGoogle({area:'IITM',label:'Personal transport'});await service.sync(account.id);provider.title='2-Step Verification turned on';provider.sender='Google Accounts <no-reply@accounts.google.com>';provider.rawMetadata={to:'personal@example.com',labelIds:['INBOX']};await service.sync(account.id);const first=service.reevaluateInbox(account.id);const second=service.reevaluateInbox(account.id);expect(first.archived).toBe(1);expect(second.archived).toBe(1);expect((db.prepare("SELECT count(*) n FROM review_proposals p JOIN external_records e ON e.id=p.external_record_id WHERE p.status='pending' AND e.provider='google'").get() as any).n).toBe(0);expect((db.prepare("SELECT count(*) n FROM external_records WHERE provider='google'").get() as any).n).toBe(1)});
});
